<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/AC',
    'key' => 'AC',
    'name' => 'ASCENSION ISLAND',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C%n%Z',
    'lfmt' => null,
    'require' => [],
    'upper' => [],
    'zip' => 'ASCN 1ZZ',
    'zipex' => ['ASCN 1ZZ'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
