<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/AD',
    'key' => 'AD',
    'name' => 'ANDORRA',
    'lang' => 'ca',
    'languages' => ['ca'],
    'fmt' => '%N%n%O%n%A%n%Z %C',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => 'AD[1-7]0\\d',
    'zipex' => ['AD100', 'AD501', 'AD700'],
    'posturl' => 'http://www.correos.es/comun/CodigosPostales/1010_s-CodPostal.asp?Provincia=',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Parròquia d\'Andorra la Vella', 'Canillo', 'Encamp', 'Escaldes-Engordany', 'La Massana', 'Ordino', 'Sant Julià de Lòria'],
    'sub_names' => ['Andorra la Vella', 'Canillo', 'Encamp', 'Escaldes-Engordany', 'La Massana', 'Ordino', 'Sant Julià de Lòria'],
    'sub_lnames' => [],
    'sub_zips' => ['AD50[01]', 'AD10[01]', 'AD20[01]', 'AD70[01]', 'AD40[01]', 'AD30[01]', 'AD60[01]'],
    'sub_zipexs' => ['AD500', 'AD100', 'AD200', 'AD700', 'AD400', 'AD300', 'AD600'],
    'sub_isoids' => ['07', '02', '03', '08', '04', '05', '06'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
