<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/AE',
    'key' => 'AE',
    'name' => 'UNITED ARAB EMIRATES',
    'lang' => 'ar',
    'languages' => ['ar'],
    'fmt' => '%N%n%O%n%A%n%S',
    'lfmt' => '%N%n%O%n%A%n%S',
    'require' => ['A', 'S'],
    'upper' => ['C'],
    'zip' => null,
    'zipex' => [],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'emirate',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['أبو ظبي', 'إمارة الشارقةّ', 'الفجيرة', 'ام القيوين', 'إمارة دبيّ', 'إمارة رأس الخيمة', 'عجمان'],
    'sub_names' => ['أبو ظبي', 'الشارقة', 'الفجيرة', 'ام القيوين', 'دبي', 'رأس الخيمة', 'عجمان'],
    'sub_lnames' => ['Abu Dhabi', 'Sharjah', 'Fujairah', 'Umm Al Quwain', 'Dubai', 'Ras al Khaimah', 'Ajman'],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['AZ', 'SH', 'FU', 'UQ', 'DU', 'RK', 'AJ'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
