<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/AL',
    'key' => 'AL',
    'name' => 'ALBANIA',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z%n%C',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => '\\d{4}',
    'zipex' => ['1001', '1017', '3501'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
