<?php return \Sunaoka\AddressData\Address::__set_state(array(
   'id' => 'data/AR',
   'key' => 'AR',
   'name' => 'ARGENTINA',
   'lang' => 'es',
   'languages' => 
  array (
    0 => 'es',
  ),
   'fmt' => '%N%n%O%n%A%n%Z %C%n%S',
   'lfmt' => NULL,
   'require' => 
  array (
  ),
   'upper' => 
  array (
    0 => 'A',
    1 => 'C',
    2 => 'Z',
  ),
   'zip' => '((?:[A-HJ-NP-Z])?\\d{4})([A-Z]{3})?',
   'zipex' => 
  array (
    0 => 'C1070AAM',
    1 => 'C1000WAM',
    2 => 'B1000TBU',
    3 => 'X5187XAB',
  ),
   'posturl' => 'http://www.correoargentino.com.ar/formularios/cpa',
   'postprefix' => NULL,
   'zip_name_type' => NULL,
   'state_name_type' => NULL,
   'locality_name_type' => NULL,
   'sublocality_name_type' => NULL,
   'sub_keys' => 
  array (
    0 => 'Buenos Aires',
    1 => 'Catamarca',
    2 => 'Chaco',
    3 => 'Chubut',
    4 => 'Ciudad Autónoma de Buenos Aires',
    5 => 'Córdoba',
    6 => 'Corrientes',
    7 => 'Entre Ríos',
    8 => 'Formosa',
    9 => 'Jujuy',
    10 => 'La Pampa',
    11 => 'La Rioja',
    12 => 'Mendoza',
    13 => 'Misiones',
    14 => 'Neuquén',
    15 => 'Río Negro',
    16 => 'Salta',
    17 => 'San Juan',
    18 => 'San Luis',
    19 => 'Santa Cruz',
    20 => 'Santa Fe',
    21 => 'Santiago del Estero',
    22 => 'Tierra del Fuego',
    23 => 'Tucumán',
  ),
   'sub_names' => 
  array (
    0 => 'Buenos Aires',
    1 => 'Catamarca',
    2 => 'Chaco',
    3 => 'Chubut',
    4 => 'Ciudad Autónoma de Buenos Aires',
    5 => 'Córdoba',
    6 => 'Corrientes',
    7 => 'Entre Ríos',
    8 => 'Formosa',
    9 => 'Jujuy',
    10 => 'La Pampa',
    11 => 'La Rioja',
    12 => 'Mendoza',
    13 => 'Misiones',
    14 => 'Neuquén',
    15 => 'Río Negro',
    16 => 'Salta',
    17 => 'San Juan',
    18 => 'San Luis',
    19 => 'Santa Cruz',
    20 => 'Santa Fe',
    21 => 'Santiago del Estero',
    22 => 'Tierra del Fuego',
    23 => 'Tucumán',
  ),
   'sub_lnames' => 
  array (
  ),
   'sub_zips' => 
  array (
    0 => 'B?[1-36-8]',
    1 => 'K?[45]',
    2 => 'H?3',
    3 => 'U?[89]',
    4 => 'C?1',
    5 => 'X?[235-8]',
    6 => 'W?3',
    7 => 'E?[1-3]',
    8 => 'P?[37]',
    9 => 'Y?4',
    10 => 'L?[3568]',
    11 => 'F?5',
    12 => 'M?[56]',
    13 => 'N?3',
    14 => 'Q?[38]',
    15 => 'R?[89]',
    16 => 'A?[34]',
    17 => 'J?5',
    18 => 'D?[4-6]',
    19 => 'Z?[89]',
    20 => 'S?[2368]',
    21 => 'G?[2-5]',
    22 => 'V?9',
    23 => 'T?[45]',
  ),
   'sub_zipexs' => 
  array (
  ),
   'sub_isoids' => 
  array (
    0 => 'B',
    1 => 'K',
    2 => 'H',
    3 => 'U',
    4 => 'C',
    5 => 'X',
    6 => 'W',
    7 => 'E',
    8 => 'P',
    9 => 'Y',
    10 => 'L',
    11 => 'F',
    12 => 'M',
    13 => 'N',
    14 => 'Q',
    15 => 'R',
    16 => 'A',
    17 => 'J',
    18 => 'D',
    19 => 'Z',
    20 => 'S',
    21 => 'G',
    22 => 'V',
    23 => 'T',
  ),
   'sub_mores' => 
  array (
  ),
   'sub_xzips' => 
  array (
  ),
   'sub_xrequires' => 
  array (
  ),
));