<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/AX',
    'key' => 'AX',
    'name' => 'FINLAND',
    'lang' => null,
    'languages' => [],
    'fmt' => '%O%n%N%n%A%nAX-%Z %C%nÅLAND',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['C'],
    'zip' => '22\\d{3}',
    'zipex' => ['22150', '22550', '22240', '22710', '22270', '22730', '22430'],
    'posturl' => 'https://www.alandpost.ax/privat/skicka-brev/postnummer-pa-aland/postnummersokning',
    'postprefix' => 'AX-',
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
