<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/AZ',
    'key' => 'AZ',
    'name' => 'AZERBAIJAN',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%nAZ %Z %C',
    'lfmt' => null,
    'require' => [],
    'upper' => [],
    'zip' => '\\d{4}',
    'zipex' => ['1000'],
    'posturl' => null,
    'postprefix' => 'AZ ',
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
