<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/BB',
    'key' => 'BB',
    'name' => 'BARBADOS',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C, %S %Z',
    'lfmt' => null,
    'require' => [],
    'upper' => [],
    'zip' => 'BB\\d{5}',
    'zipex' => ['BB23026', 'BB22025'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => 'parish',
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
