<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/BD',
    'key' => 'BD',
    'name' => 'BANGLADESH',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C - %Z',
    'lfmt' => null,
    'require' => [],
    'upper' => [],
    'zip' => '\\d{4}',
    'zipex' => ['1340', '1000'],
    'posturl' => 'https://bdpost.portal.gov.bd/site/page/f41a42bd-2540-4afa-8568-af56443c3df8/-',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
