<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/BG',
    'key' => 'BG',
    'name' => 'BULGARIA (REP.)',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z %C',
    'lfmt' => null,
    'require' => [],
    'upper' => [],
    'zip' => '\\d{4}',
    'zipex' => ['1000', '1700'],
    'posturl' => 'http://www.bgpost.bg/?cid=5',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
