<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/BH',
    'key' => 'BH',
    'name' => 'BAHRAIN',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C %Z',
    'lfmt' => null,
    'require' => [],
    'upper' => [],
    'zip' => '(?:^|\\b)(?:1[0-2]|[1-9])\\d{2}(?:$|\\b)',
    'zipex' => ['317'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
