<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/BN',
    'key' => 'BN',
    'name' => 'BRUNEI DARUSSALAM',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C %Z',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => '[A-Z]{2} ?\\d{4}',
    'zipex' => ['BT2328', 'KA1131', 'BA1511'],
    'posturl' => 'http://www.post.gov.bn/SitePages/postcodes.aspx',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
