<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/BS',
    'key' => 'BS',
    'name' => 'BAHAMAS',
    'lang' => 'en',
    'languages' => ['en'],
    'fmt' => '%N%n%O%n%A%n%C, %S',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => null,
    'zipex' => [],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'island',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Abaco', 'Acklins', 'Andros', 'Berry Islands', 'Bimini', 'Cat Island', 'Crooked Island', 'Eleuthera', 'Exuma', 'Grand Bahama', 'Harbour Island', 'Inagua', 'Long Island', 'Mayaguana', 'N.P.', 'Ragged Island', 'Rum Cay', 'San Salvador', 'Spanish Wells'],
    'sub_names' => ['Abaco Islands', 'Acklins', 'Andros Island', 'Berry Islands', 'Bimini', 'Cat Island', 'Crooked Island', 'Eleuthera', 'Exuma and Cays', 'Grand Bahama', 'Harbour Island', 'Inagua', 'Long Island', 'Mayaguana', 'New Providence', 'Ragged Island', 'Rum Cay', 'San Salvador', 'Spanish Wells'],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['', 'AK', '', 'BY', 'BI', 'CI', '', '', 'EX', '', 'HI', 'IN', 'LI', 'MG', '', 'RI', 'RC', 'SS', 'SW'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
