<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/BY',
    'key' => 'BY',
    'name' => 'BELARUS',
    'lang' => 'be',
    'languages' => ['be', 'ru'],
    'fmt' => '%O%n%N%n%A%n%Z, %C%n%S',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => '\\d{6}',
    'zipex' => ['223016', '225860', '220050'],
    'posturl' => 'http://ex.belpost.by/addressbook/',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Брэсцкая вобласць', 'Віцебская вобласць', 'Гомельская вобласць', 'горад Мінск', 'Гродзенская вобласць', 'Магілёўская вобласць', 'Мінская вобласць'],
    'sub_names' => [],
    'sub_lnames' => ['Bresckaja voblasć', 'Viciebskaja voblasć', 'Homieĺskaja voblasć', 'Horad Minsk', 'Hrodzienskaja voblasć', 'Mahilioŭskaja voblasć', 'Minskaja voblasć'],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['BR', 'VI', 'HO', 'HM', 'HR', 'MA', 'MI'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
