<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/BY',
    'key' => 'BY',
    'name' => 'BELARUS',
    'lang' => null,
    'languages' => [],
    'fmt' => '%O%n%N%n%A%n%Z, %C%n%S',
    'lfmt' => null,
    'require' => [],
    'upper' => [],
    'zip' => '\\d{6}',
    'zipex' => ['223016', '225860', '220050'],
    'posturl' => 'http://ex.belpost.by/addressbook/',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
