<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/CA',
    'key' => 'CA',
    'name' => 'CANADA',
    'lang' => 'en',
    'languages' => ['en', 'fr'],
    'fmt' => '%N%n%O%n%A%n%C %S %Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'S', 'Z'],
    'upper' => ['A', 'C', 'N', 'O', 'S', 'Z'],
    'zip' => '[ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJ-NPRSTV-Z] ?\\d[ABCEGHJ-NPRSTV-Z]\\d',
    'zipex' => ['H3Z 2Y7', 'V8X 3X4', 'T0L 1K0', 'T0H 1A0', 'K1A 0B1'],
    'posturl' => 'https://www.canadapost.ca/cpo/mc/personal/postalcode/fpc.jsf',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['AB', 'BC', 'MB', 'NB', 'NL', 'NT', 'NS', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT'],
    'sub_names' => ['Alberta', 'British Columbia', 'Manitoba', 'New Brunswick', 'Newfoundland and Labrador', 'Northwest Territories', 'Nova Scotia', 'Nunavut', 'Ontario', 'Prince Edward Island', 'Quebec', 'Saskatchewan', 'Yukon'],
    'sub_lnames' => [],
    'sub_zips' => ['T', 'V', 'R', 'E', 'A', 'X0E|X0G|X1A', 'B', 'X0A|X0B|X0C', 'K|L|M|N|P', 'C', 'G|H|J|K1A', 'S|R8A', 'Y'],
    'sub_zipexs' => [],
    'sub_isoids' => ['AB', 'BC', 'MB', 'NB', 'NL', 'NT', 'NS', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
