<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/CC',
    'key' => 'CC',
    'name' => 'COCOS (KEELING) ISLANDS',
    'lang' => null,
    'languages' => [],
    'fmt' => '%O%n%N%n%A%n%C %S %Z',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C', 'S'],
    'zip' => '6799',
    'zipex' => ['6799'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
