<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/CH',
    'key' => 'CH',
    'name' => 'SWITZERLAND',
    'lang' => null,
    'languages' => [],
    'fmt' => '%O%n%N%n%A%nCH-%Z %C',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => [''],
    'zip' => '\\d{4}',
    'zipex' => ['2544', '1211', '1556', '3030'],
    'posturl' => 'http://www.post.ch/db/owa/pv_plz_pack/pr_main',
    'postprefix' => 'CH-',
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
