<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/CR',
    'key' => 'CR',
    'name' => 'COSTA RICA',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%S, %C%n%Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'S'],
    'upper' => [],
    'zip' => '\\d{4,5}|\\d{3}-\\d{4}',
    'zipex' => ['1000', '2010', '1001'],
    'posturl' => 'https://correos.go.cr/codigo-postal/',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
