<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/CU',
    'key' => 'CU',
    'name' => 'CUBA',
    'lang' => 'es',
    'languages' => ['es'],
    'fmt' => '%N%n%O%n%A%n%C %S%n%Z',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => '\\d{5}',
    'zipex' => ['10700'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Artemisa', 'Camagüey', 'Ciego de Ávila', 'Cienfuegos', 'Granma', 'Guantánamo', 'Holguín', 'Isla de la Juventud', 'La Habana', 'Las Tunas', 'Matanzas', 'Mayabeque', 'Pinar del Río', 'Sancti Spíritus', 'Santiago de Cuba', 'Villa Clara'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['15', '09', '08', '06', '12', '14', '11', '99', '03', '10', '04', '16', '01', '07', '13', '05'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
