<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/CV',
    'key' => 'CV',
    'name' => 'CAPE VERDE',
    'lang' => 'pt',
    'languages' => ['pt'],
    'fmt' => '%N%n%O%n%A%n%Z %C%n%S',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => '\\d{4}',
    'zipex' => ['7600'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'island',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Boa Vista', 'Brava', 'Fogo', 'Maio', 'Sal', 'Santiago', 'Santo Antão', 'São Nicolau', 'São Vicente'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['BV', 'BR', '', 'MA', 'SL', '', '', '', 'SV'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
