<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/CZ',
    'key' => 'CZ',
    'name' => 'CZECH REP.',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z %C',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => [],
    'zip' => '\\d{3} ?\\d{2}',
    'zipex' => ['100 00', '251 66', '530 87', '110 00', '225 99'],
    'posturl' => 'http://psc.ceskaposta.cz/CleanForm.action',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
