<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/DK',
    'key' => 'DK',
    'name' => 'DENMARK',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z %C',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => [],
    'zip' => '\\d{4}',
    'zipex' => ['8660', '1566'],
    'posturl' => 'http://www.postdanmark.dk/da/Privat/Kundeservice/postnummerkort/Sider/Find-postnummer.aspx',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
