<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/EC',
    'key' => 'EC',
    'name' => 'ECUADOR',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z%n%C',
    'lfmt' => null,
    'require' => [],
    'upper' => ['C', 'Z'],
    'zip' => '\\d{6}',
    'zipex' => ['090105', '092301'],
    'posturl' => 'http://www.codigopostal.gob.ec/',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
