<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/EE',
    'key' => 'EE',
    'name' => 'ESTONIA',
    'lang' => 'et',
    'languages' => ['et'],
    'fmt' => '%N%n%O%n%A%n%Z %C %S',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['C'],
    'zip' => '\\d{5}',
    'zipex' => ['69501', '11212'],
    'posturl' => 'https://www.omniva.ee/era/sihtnumbrite_otsing',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Harjumaa', 'Hiiumaa', 'Ida-Virumaa', 'Jõgevamaa', 'Järvamaa', 'Lääne-Virumaa', 'Läänemaa', 'Põlvamaa', 'Pärnumaa', 'Raplamaa', 'Saaremaa', 'Tartumaa', 'Valgamaa', 'Viljandimaa', 'Võrumaa'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['37', '39', '45', '50', '52', '60', '56', '64', '68', '71', '74', '79', '81', '84', '87'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
