<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/EE',
    'key' => 'EE',
    'name' => 'ESTONIA',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z %C %S',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => [],
    'zip' => '\\d{5}',
    'zipex' => ['69501', '11212'],
    'posturl' => 'https://www.omniva.ee/era/sihtnumbrite_otsing',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
