<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/EG',
    'key' => 'EG',
    'name' => 'EGYPT',
    'lang' => 'ar',
    'languages' => ['ar'],
    'fmt' => '%N%n%O%n%A%n%C%n%S%n%Z',
    'lfmt' => '%N%n%O%n%A%n%C%n%S%n%Z',
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => '\\d{7}|\\d{5}',
    'zipex' => ['4460232', '5734356'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['أسوان', 'أسيوط', 'الإسكندرية', 'الإسماعيلية', 'الأقصر', 'البحر الأحمر', 'البحيرة', 'الجيزة', 'الدقهلية', 'السويس', 'الشرقية', 'الغربية', 'الفيوم', 'القاهرة', 'القليوبية', 'المنوفية', 'المنيا', 'الوادي الجديد', 'بني سويف', 'بورسعيد', 'جنوب سيناء', 'دمياط', 'سوهاج', 'شمال سيناء', 'قنا', 'كفر الشيخ', 'مطروح'],
    'sub_names' => [],
    'sub_lnames' => ['Aswan Governorate', 'Asyut Governorate', 'Alexandria Governorate', 'Ismailia Governorate', 'Luxor Governorate', 'Red Sea Governorate', 'El Beheira Governorate', 'Giza Governorate', 'Dakahlia Governorate', 'Suez Governorate', 'Ash Sharqia Governorate', 'Gharbia Governorate', 'Faiyum Governorate', 'Cairo Governorate', 'Qalyubia Governorate', 'Menofia Governorate', 'Menia Governorate', 'New Valley Governorate', 'Beni Suef Governorate', 'Port Said Governorate', 'South Sinai Governorate', 'Damietta Governorate', 'Sohag Governorate', 'North Sinai Governorate', 'Qena Governorate', 'Kafr El Sheikh Governorate', 'Matrouh Governorate'],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['ASN', 'AST', 'ALX', 'IS', 'LX', 'BA', 'BH', 'GZ', 'DK', 'SUZ', 'SHR', 'GH', 'FYM', 'C', 'KB', 'MNF', 'MN', 'WAD', 'BNS', 'PTS', 'JS', 'DT', 'SHG', 'SIN', 'KN', 'KFS', 'MT'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
