<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/ES',
    'key' => 'ES',
    'name' => 'SPAIN',
    'lang' => 'es',
    'languages' => ['es', 'ca', 'gl', 'eu'],
    'fmt' => '%N%n%O%n%A%n%Z %C %S',
    'lfmt' => null,
    'require' => ['A', 'C', 'S', 'Z'],
    'upper' => ['C', 'S'],
    'zip' => '\\d{5}',
    'zipex' => ['28039', '28300', '28070'],
    'posturl' => 'http://www.correos.es/contenido/13-MenuRec2/04-MenuRec24/1010_s-CodPostal.asp',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['VI', 'AB', 'A', 'AL', 'O', 'AV', 'BA', 'B', 'BU', 'CC', 'CA', 'S', 'CS', 'CE', 'CR', 'CO', 'CU', 'GI', 'GR', 'GU', 'SS', 'H', 'HU', 'PM', 'J', 'C', 'LO', 'GC', 'LE', 'L', 'LU', 'M', 'MA', 'ML', 'MU', 'NA', 'OR', 'P', 'PO', 'SA', 'TF', 'SG', 'SE', 'SO', 'T', 'TE', 'TO', 'V', 'VA', 'BI', 'ZA', 'Z'],
    'sub_names' => ['Álava', 'Albacete', 'Alicante', 'Almería', 'Asturias', 'Ávila', 'Badajoz', 'Barcelona', 'Burgos', 'Cáceres', 'Cádiz', 'Cantabria', 'Castellón', 'Ceuta', 'Ciudad Real', 'Córdoba', 'Cuenca', 'Girona', 'Granada', 'Guadalajara', 'Guipúzcoa', 'Huelva', 'Huesca', 'Islas Baleares', 'Jaén', 'La Coruña', 'La Rioja', 'Las Palmas', 'León', 'Lérida', 'Lugo', 'Madrid', 'Málaga', 'Melilla', 'Murcia', 'Navarra', 'Ourense', 'Palencia', 'Pontevedra', 'Salamanca', 'Santa Cruz de Tenerife', 'Segovia', 'Sevilla', 'Soria', 'Tarragona', 'Teruel', 'Toledo', 'Valencia', 'Valladolid', 'Vizcaya', 'Zamora', 'Zaragoza'],
    'sub_lnames' => [],
    'sub_zips' => ['01', '02', '03', '04', '33', '05', '06', '08', '09', '10', '11', '39', '12', '51', '13', '14', '16', '17', '18', '19', '20', '21', '22', '07', '23', '15', '26', '35', '24', '25', '27', '28', '29', '52', '30', '31', '32', '34', '36', '37', '38', '40', '41', '26127|42', '43', '44', '45', '46', '47', '48', '49', '50'],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
