<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/FI',
    'key' => 'FI',
    'name' => 'FINLAND',
    'lang' => null,
    'languages' => [],
    'fmt' => '%O%n%N%n%A%nFI-%Z %C',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['C'],
    'zip' => '\\d{5}',
    'zipex' => ['00550', '00011'],
    'posturl' => 'https://support.posti.fi/fi/tyokalut/postinumerohaku.html',
    'postprefix' => 'FI-',
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
