<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/FM',
    'key' => 'FM',
    'name' => 'MICRONESIA (Federated State of)',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C %S %Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'S', 'Z'],
    'upper' => ['A', 'C', 'N', 'O', 'S'],
    'zip' => '(9694[1-4])(?:[ \\-](\\d{4}))?',
    'zipex' => ['96941', '96944'],
    'posturl' => 'http://zip4.usps.com/zip4/welcome.jsp',
    'postprefix' => null,
    'zip_name_type' => 'zip',
    'state_name_type' => 'state',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
