<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/FO',
    'key' => 'FO',
    'name' => 'FAROE ISLANDS',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%nFO%Z %C',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => '\\d{3}',
    'zipex' => ['100'],
    'posturl' => 'https://www.posta.fo/fo/forsida/finn-postnr-stad/',
    'postprefix' => 'FO',
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
