<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/GI',
    'key' => 'GI',
    'name' => 'GIBRALTAR',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%nGIBRALTAR%n%Z',
    'lfmt' => null,
    'require' => ['A'],
    'upper' => [],
    'zip' => 'GX11 1AA',
    'zipex' => ['GX11 1AA'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
