<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/GR',
    'key' => 'GR',
    'name' => 'GREECE',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z %C',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => [],
    'zip' => '\\d{3} ?\\d{2}',
    'zipex' => ['151 24', '151 10', '101 88'],
    'posturl' => 'http://www.elta.gr/findapostcode.aspx',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
