<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/GS',
    'key' => 'GS',
    'name' => 'SOUTH GEORGIA',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%n%C%n%Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['C', 'Z'],
    'zip' => 'SIQQ 1ZZ',
    'zipex' => ['SIQQ 1ZZ'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
