<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/GU',
    'key' => 'GU',
    'name' => 'GUAM',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C %Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['A', 'C', 'N', 'O'],
    'zip' => '(969(?:[12]\\d|3[12]))(?:[ \\-](\\d{4}))?',
    'zipex' => ['96910', '96931'],
    'posturl' => 'http://zip4.usps.com/zip4/welcome.jsp',
    'postprefix' => null,
    'zip_name_type' => 'zip',
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
