<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/HK',
    'key' => 'HK',
    'name' => 'HONG KONG',
    'lang' => 'zh-Hant',
    'languages' => ['zh-Hant', 'en'],
    'fmt' => '%S%n%C%n%A%n%O%n%N',
    'lfmt' => '%N%n%O%n%A%n%C%n%S',
    'require' => ['A', 'S'],
    'upper' => ['S'],
    'zip' => null,
    'zipex' => [],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'area',
    'locality_name_type' => 'district',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Kowloon', 'Hong Kong Island', 'New Territories'],
    'sub_names' => ['九龍', '香港島', '新界'],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => ['true', 'true', 'true'],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
