<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/HN',
    'key' => 'HN',
    'name' => 'HONDURAS',
    'lang' => 'es',
    'languages' => ['es'],
    'fmt' => '%N%n%O%n%A%n%C, %S%n%Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'S'],
    'upper' => ['C'],
    'zip' => '\\d{5}',
    'zipex' => ['31301'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'department',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Atlántida', 'Choluteca', 'Colón', 'Comayagua', 'Copán', 'Cortés', 'El Paraíso', 'Francisco Morazán', 'Gracias a Dios', 'Intibucá', 'Islas de la Bahía', 'La Paz', 'Lempira', 'Ocotepeque', 'Olancho', 'Santa Bárbara', 'Valle', 'Yoro'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['AT', 'CH', 'CL', 'CM', 'CP', 'CR', 'EP', 'FM', 'GD', 'IN', 'IB', 'LP', 'LE', 'OC', 'OL', 'SB', 'VA', 'YO'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
