<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/HR',
    'key' => 'HR',
    'name' => 'CROATIA',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%nHR-%Z %C',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => '\\d{5}',
    'zipex' => ['10000', '21001', '10002'],
    'posturl' => 'http://www.posta.hr/default.aspx?pretpum',
    'postprefix' => 'HR-',
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
