<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/HU',
    'key' => 'HU',
    'name' => 'HUNGARY (Rep.)',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%C%n%A%n%Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['A', 'C', 'N', 'O'],
    'zip' => '\\d{4}',
    'zipex' => ['1037', '2380', '1540'],
    'posturl' => 'http://posta.hu/ugyfelszolgalat/iranyitoszam_kereso',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
