<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/ID',
    'key' => 'ID',
    'name' => 'INDONESIA',
    'lang' => 'id',
    'languages' => ['id'],
    'fmt' => '%N%n%O%n%A%n%C%n%S %Z',
    'lfmt' => null,
    'require' => ['A', 'S'],
    'upper' => [],
    'zip' => '\\d{5}',
    'zipex' => ['40115'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => ['Aceh', 'Bali', 'Banten', 'Bengkulu', 'Daerah Istimewa Yogyakarta', 'DKI Jakarta', 'Gorontalo', 'Jambi', 'Jawa Barat', 'Jawa Tengah', 'Jawa Timur', 'Kalimantan Barat', 'Kalimantan Selatan', 'Kalimantan Tengah', 'Kalimantan Timur', 'Kalimantan Utara', 'Kepulauan Bangka Belitung', 'Kepulauan Riau', 'Lampung', 'Maluku', 'Maluku Utara', 'Nusa Tenggara Barat', 'Nusa Tenggara Timur', 'Papua', 'Papua Barat', 'Riau', 'Sulawesi Barat', 'Sulawesi Selatan', 'Sulawesi Tengah', 'Sulawesi Tenggara', 'Sulawesi Utara', 'Sumatera Barat', 'Sumatera Selatan', 'Sumatera Utara'],
    'sub_names' => [],
    'sub_lnames' => ['Aceh', 'Bali', 'Banten', 'Bengkulu', 'Special Region of Yogyakarta', 'Jakarta', 'Gorontalo', 'Jambi', 'West Java', 'Central Java', 'East Java', 'West Kalimantan', 'South Kalimantan', 'Central Kalimantan', 'East Kalimantan', 'North Kalimantan', 'Bangka Belitung Islands', 'Riau Islands', 'Lampung', 'Maluku', 'North Maluku', 'West Nusa Tenggara', 'East Nusa Tenggara', 'Papua', 'West Papua', 'Riau', 'West Sulawesi', 'South Sulawesi', 'Central Sulawesi', 'South East Sulawesi', 'North Sulawesi', 'West Sumatra', 'South Sumatra', 'North Sumatra'],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['AC', 'BA', 'BT', 'BE', 'YO', 'JK', 'GO', 'JA', 'JB', 'JT', 'JI', 'KB', 'KS', 'KT', 'KI', 'KU', 'BB', 'KR', 'LA', 'MA', 'MU', 'NB', 'NT', 'PA', 'PB', 'RI', 'SR', 'SN', 'ST', 'SG', 'SA', 'SB', 'SS', 'SU'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
