<?php return \Sunaoka\AddressData\Address::__set_state(array(
   'id' => 'data/ID',
   'key' => 'ID',
   'name' => 'INDONESIA',
   'lang' => 'id',
   'languages' => 
  array (
    0 => 'id',
  ),
   'fmt' => '%N%n%O%n%A%n%C%n%S %Z',
   'lfmt' => NULL,
   'require' => 
  array (
    0 => 'A',
    1 => 'S',
  ),
   'upper' => 
  array (
  ),
   'zip' => '\\d{5}',
   'zipex' => 
  array (
    0 => '40115',
  ),
   'posturl' => NULL,
   'postprefix' => NULL,
   'zip_name_type' => NULL,
   'state_name_type' => NULL,
   'locality_name_type' => NULL,
   'sublocality_name_type' => NULL,
   'sub_keys' => 
  array (
    0 => 'Aceh',
    1 => 'Bali',
    2 => 'Banten',
    3 => 'Bengkulu',
    4 => 'Daerah Istimewa Yogyakarta',
    5 => 'DKI Jakarta',
    6 => 'Gorontalo',
    7 => 'Jambi',
    8 => 'Jawa Barat',
    9 => 'Jawa Tengah',
    10 => 'Jawa Timur',
    11 => 'Kalimantan Barat',
    12 => 'Kalimantan Selatan',
    13 => 'Kalimantan Tengah',
    14 => 'Kalimantan Timur',
    15 => 'Kalimantan Utara',
    16 => 'Kepulauan Bangka Belitung',
    17 => 'Kepulauan Riau',
    18 => 'Lampung',
    19 => 'Maluku',
    20 => 'Maluku Utara',
    21 => 'Nusa Tenggara Barat',
    22 => 'Nusa Tenggara Timur',
    23 => 'Papua',
    24 => 'Papua Barat',
    25 => 'Riau',
    26 => 'Sulawesi Barat',
    27 => 'Sulawesi Selatan',
    28 => 'Sulawesi Tengah',
    29 => 'Sulawesi Tenggara',
    30 => 'Sulawesi Utara',
    31 => 'Sumatera Barat',
    32 => 'Sumatera Selatan',
    33 => 'Sumatera Utara',
  ),
   'sub_names' => 
  array (
  ),
   'sub_lnames' => 
  array (
    0 => 'Aceh',
    1 => 'Bali',
    2 => 'Banten',
    3 => 'Bengkulu',
    4 => 'Special Region of Yogyakarta',
    5 => 'Jakarta',
    6 => 'Gorontalo',
    7 => 'Jambi',
    8 => 'West Java',
    9 => 'Central Java',
    10 => 'East Java',
    11 => 'West Kalimantan',
    12 => 'South Kalimantan',
    13 => 'Central Kalimantan',
    14 => 'East Kalimantan',
    15 => 'North Kalimantan',
    16 => 'Bangka Belitung Islands',
    17 => 'Riau Islands',
    18 => 'Lampung',
    19 => 'Maluku',
    20 => 'North Maluku',
    21 => 'West Nusa Tenggara',
    22 => 'East Nusa Tenggara',
    23 => 'Papua',
    24 => 'West Papua',
    25 => 'Riau',
    26 => 'West Sulawesi',
    27 => 'South Sulawesi',
    28 => 'Central Sulawesi',
    29 => 'South East Sulawesi',
    30 => 'North Sulawesi',
    31 => 'West Sumatra',
    32 => 'South Sumatra',
    33 => 'North Sumatra',
  ),
   'sub_zips' => 
  array (
  ),
   'sub_zipexs' => 
  array (
  ),
   'sub_isoids' => 
  array (
    0 => 'AC',
    1 => 'BA',
    2 => 'BT',
    3 => 'BE',
    4 => 'YO',
    5 => 'JK',
    6 => 'GO',
    7 => 'JA',
    8 => 'JB',
    9 => 'JT',
    10 => 'JI',
    11 => 'KB',
    12 => 'KS',
    13 => 'KT',
    14 => 'KI',
    15 => 'KU',
    16 => 'BB',
    17 => 'KR',
    18 => 'LA',
    19 => 'MA',
    20 => 'MU',
    21 => 'NB',
    22 => 'NT',
    23 => 'PA',
    24 => 'PB',
    25 => 'RI',
    26 => 'SR',
    27 => 'SN',
    28 => 'ST',
    29 => 'SG',
    30 => 'SA',
    31 => 'SB',
    32 => 'SS',
    33 => 'SU',
  ),
   'sub_mores' => 
  array (
  ),
   'sub_xzips' => 
  array (
  ),
   'sub_xrequires' => 
  array (
  ),
));