<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/IE',
    'key' => 'IE',
    'name' => 'IRELAND',
    'lang' => 'en',
    'languages' => ['en'],
    'fmt' => '%N%n%O%n%A%n%D%n%C%n%S%n%Z',
    'lfmt' => null,
    'require' => [],
    'upper' => [],
    'zip' => '[\\dA-Z]{3} ?[\\dA-Z]{4}',
    'zipex' => ['A65 F4E2'],
    'posturl' => 'https://finder.eircode.ie',
    'postprefix' => null,
    'zip_name_type' => 'eircode',
    'state_name_type' => 'county',
    'locality_name_type' => null,
    'sublocality_name_type' => 'townland',
    'sub_keys' => ['Co. Carlow', 'Co. Cavan', 'Co. Clare', 'Co. Cork', 'Co. Donegal', 'Co. Dublin', 'Co. Galway', 'Co. Kerry', 'Co. Kildare', 'Co. Kilkenny', 'Co. Laois', 'Co. Leitrim', 'Co. Limerick', 'Co. Longford', 'Co. Louth', 'Co. Mayo', 'Co. Meath', 'Co. Monaghan', 'Co. Offaly', 'Co. Roscommon', 'Co. Sligo', 'Co. Tipperary', 'Co. Waterford', 'Co. Westmeath', 'Co. Wexford', 'Co. Wicklow'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['CW', 'CN', 'CE', 'CO', 'DL', 'D', 'G', 'KY', 'KE', 'KK', 'LS', 'LM', 'LK', 'LD', 'LH', 'MO', 'MH', 'MN', 'OY', 'RN', 'SO', 'TA', 'WD', 'WH', 'WX', 'WW'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
