<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/IL',
    'key' => 'IL',
    'name' => 'ISRAEL',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C %Z',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => '\\d{5}(?:\\d{2})?',
    'zipex' => ['9614303'],
    'posturl' => 'http://www.israelpost.co.il/zipcode.nsf/demozip?openform',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
