<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/IM',
    'key' => 'IM',
    'name' => 'ISLE OF MAN',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C%n%Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['C', 'Z'],
    'zip' => 'IM\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}',
    'zipex' => ['IM2 1AA', 'IM99 1PS'],
    'posturl' => 'https://www.iompost.com/tools-forms/postcode-finder/',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
