<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/IQ',
    'key' => 'IQ',
    'name' => 'IRAQ',
    'lang' => 'ar',
    'languages' => ['ar'],
    'fmt' => '%O%n%N%n%A%n%C, %S%n%Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'S'],
    'upper' => ['C', 'S'],
    'zip' => '\\d{5}',
    'zipex' => ['31001'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['أربيل', 'إقليم كوردستان', 'الانبار', 'البصرة', 'السليمانية', 'القادسية', 'المثنى', 'النجف', 'بابل', 'بغداد', 'دهوك', 'ديالى', 'ذي قار', 'صلاح الدين', 'كربلاء', 'كركوك', 'ميسان', 'نينوى', 'واسط'],
    'sub_names' => [],
    'sub_lnames' => ['Erbil', 'Kurdistan Region', 'Al Anbar', 'Basra', 'Sulaymaniyah', 'Al-Qādisiyyah', 'Al Muthanna', 'Najaf', 'Babylon', 'Baghdad', 'Duhok', 'Diyala', 'Dhi Qar', 'Saladin', 'Karbala', 'Kirkuk', 'Maysan', 'Nineveh', 'Wasit'],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['AR', 'KR', 'AN', 'BA', 'SU', 'QA', 'MU', 'NA', 'BB', 'BG', 'DA', 'DI', 'DQ', 'SD', 'KA', 'KI', 'MA', 'NI', 'WA'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
