<?php return Sunaoka\AddressData\Address::__set_state(array(
   'id' => 'data/IR',
   'key' => 'IR',
   'name' => 'IRAN',
   'lang' => 'fa',
   'languages' => 
  array (
    0 => 'fa',
  ),
   'fmt' => '%O%n%N%n%S%n%C, %D%n%A%n%Z',
   'lfmt' => NULL,
   'require' => 
  array (
  ),
   'upper' => 
  array (
  ),
   'zip' => '\\d{5}-?\\d{5}',
   'zipex' => 
  array (
    0 => '11936-12345',
  ),
   'posturl' => NULL,
   'postprefix' => NULL,
   'zip_name_type' => NULL,
   'state_name_type' => NULL,
   'locality_name_type' => NULL,
   'sublocality_name_type' => 'neighborhood',
   'sub_keys' => 
  array (
    0 => 'استان آذربایجان شرقی',
    1 => 'استان آذربایجان غربی',
    2 => 'استان اردبیل',
    3 => 'استان اصفهان',
    4 => 'استان البرز',
    5 => 'استان ایلام',
    6 => 'استان بوشهر',
    7 => 'استان تهران',
    8 => 'استان چهارمحال و بختیاری',
    9 => 'استان خراسان جنوبی',
    10 => 'استان خراسان رضوی',
    11 => 'استان خراسان شمالی',
    12 => 'استان خوزستان',
    13 => 'استان زنجان',
    14 => 'استان سمنان',
    15 => 'استان سیستان و بلوچستان',
    16 => 'استان فارس',
    17 => 'استان قزوین',
    18 => 'استان قم',
    19 => 'استان کردستان',
    20 => 'استان کرمان',
    21 => 'استان کرمانشاه',
    22 => 'استان کهگیلویه و بویراحمد',
    23 => 'استان گلستان',
    24 => 'استان گیلان',
    25 => 'استان لرستان',
    26 => 'استان مازندران',
    27 => 'استان مرکزی',
    28 => 'استان هرمزگان',
    29 => 'استان همدان',
    30 => 'استان یزد',
  ),
   'sub_names' => 
  array (
  ),
   'sub_lnames' => 
  array (
    0 => 'East Azerbaijan Province',
    1 => 'West Azerbaijan Province',
    2 => 'Ardabil Province',
    3 => 'Isfahan Province',
    4 => 'Alborz Province',
    5 => 'Ilam Province',
    6 => 'Bushehr Province',
    7 => 'Tehran Province',
    8 => 'Chaharmahal and Bakhtiari Province',
    9 => 'South Khorasan Province',
    10 => 'Razavi Khorasan Province',
    11 => 'North Khorasan Province',
    12 => 'Khuzestan Province',
    13 => 'Zanjan Province',
    14 => 'Semnan Province',
    15 => 'Sistan and Baluchestan Province',
    16 => 'Fars Province',
    17 => 'Qazvin Province',
    18 => 'Qom Province',
    19 => 'Kurdistan Province',
    20 => 'Kerman Province',
    21 => 'Kermanshah Province',
    22 => 'Kohgiluyeh and Boyer-Ahmad Province',
    23 => 'Golestan Province',
    24 => 'Gilan Province',
    25 => 'Lorestan Province',
    26 => 'Mazandaran Province',
    27 => 'Markazi Province',
    28 => 'Hormozgan Province',
    29 => 'Hamadan Province',
    30 => 'Yazd Province',
  ),
   'sub_zips' => 
  array (
  ),
   'sub_zipexs' => 
  array (
  ),
   'sub_isoids' => 
  array (
    0 => '03',
    1 => '04',
    2 => '24',
    3 => '10',
    4 => '30',
    5 => '16',
    6 => '18',
    7 => '23',
    8 => '14',
    9 => '29',
    10 => '09',
    11 => '28',
    12 => '06',
    13 => '19',
    14 => '20',
    15 => '11',
    16 => '07',
    17 => '26',
    18 => '25',
    19 => '12',
    20 => '08',
    21 => '05',
    22 => '17',
    23 => '27',
    24 => '01',
    25 => '15',
    26 => '02',
    27 => '00',
    28 => '22',
    29 => '13',
    30 => '21',
  ),
   'sub_mores' => 
  array (
  ),
   'sub_xzips' => 
  array (
  ),
   'sub_xrequires' => 
  array (
  ),
));