<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/IR',
    'key' => 'IR',
    'name' => 'IRAN',
    'lang' => 'fa',
    'languages' => ['fa'],
    'fmt' => '%O%n%N%n%S%n%C, %D%n%A%n%Z',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => '\\d{5}-?\\d{5}',
    'zipex' => ['11936-12345'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'neighborhood',
    'sub_keys' => ['استان آذربایجان شرقی', 'استان آذربایجان غربی', 'استان اردبیل', 'استان اصفهان', 'استان البرز', 'استان ایلام', 'استان بوشهر', 'استان تهران', 'استان چهارمحال و بختیاری', 'استان خراسان جنوبی', 'استان خراسان رضوی', 'استان خراسان شمالی', 'استان خوزستان', 'استان زنجان', 'استان سمنان', 'استان سیستان و بلوچستان', 'استان فارس', 'استان قزوین', 'استان قم', 'استان کردستان', 'استان کرمان', 'استان کرمانشاه', 'استان کهگیلویه و بویراحمد', 'استان گلستان', 'استان گیلان', 'استان لرستان', 'استان مازندران', 'استان مرکزی', 'استان هرمزگان', 'استان همدان', 'استان یزد'],
    'sub_names' => [],
    'sub_lnames' => ['East Azerbaijan Province', 'West Azerbaijan Province', 'Ardabil Province', 'Isfahan Province', 'Alborz Province', 'Ilam Province', 'Bushehr Province', 'Tehran Province', 'Chaharmahal and Bakhtiari Province', 'South Khorasan Province', 'Razavi Khorasan Province', 'North Khorasan Province', 'Khuzestan Province', 'Zanjan Province', 'Semnan Province', 'Sistan and Baluchestan Province', 'Fars Province', 'Qazvin Province', 'Qom Province', 'Kurdistan Province', 'Kerman Province', 'Kermanshah Province', 'Kohgiluyeh and Boyer-Ahmad Province', 'Golestan Province', 'Gilan Province', 'Lorestan Province', 'Mazandaran Province', 'Markazi Province', 'Hormozgan Province', 'Hamadan Province', 'Yazd Province'],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['03', '04', '24', '10', '30', '16', '18', '23', '14', '29', '09', '28', '06', '19', '20', '11', '07', '26', '25', '12', '08', '05', '17', '27', '01', '15', '02', '00', '22', '13', '21'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
