<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/IS',
    'key' => 'IS',
    'name' => 'ICELAND',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z %C',
    'lfmt' => null,
    'require' => [],
    'upper' => [],
    'zip' => '\\d{3}',
    'zipex' => ['320', '121', '220', '110'],
    'posturl' => 'https://posturinn.is/',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
