<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/JE',
    'key' => 'JE',
    'name' => 'CHANNEL ISLANDS',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C%nJERSEY%n%Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['C', 'Z'],
    'zip' => 'JE\\d[\\dA-Z]? ?\\d[ABD-HJLN-UW-Z]{2}',
    'zipex' => ['JE1 1AA', 'JE2 2BT'],
    'posturl' => 'http://www.jerseypost.com/tools/postcode-address-finder/',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
