<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/JM',
    'key' => 'JM',
    'name' => 'JAMAICA',
    'lang' => 'en',
    'languages' => ['en'],
    'fmt' => '%N%n%O%n%A%n%C%n%S %X',
    'lfmt' => null,
    'require' => ['A', 'C', 'S'],
    'upper' => ['C'],
    'zip' => null,
    'zipex' => [],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'parish',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Clarendon', 'Hanover', 'Kingston', 'Manchester', 'Portland', 'St. Andrew', 'St. Ann', 'St. Catherine', 'St. Elizabeth', 'St. James', 'St. Mary', 'St. Thomas', 'Trelawny', 'Westmoreland'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['13', '09', '01', '12', '04', '02', '06', '14', '11', '08', '05', '03', '07', '10'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
