<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/KN',
    'key' => 'KN',
    'name' => 'SAINT KITTS AND NEVIS',
    'lang' => 'en',
    'languages' => ['en'],
    'fmt' => '%N%n%O%n%A%n%C, %S',
    'lfmt' => null,
    'require' => ['A', 'C', 'S'],
    'upper' => ['C'],
    'zip' => null,
    'zipex' => [],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'island',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Nevis', 'St. Kitts'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['N', 'K'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
