<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/KP',
    'key' => 'KP',
    'name' => 'NORTH KOREA',
    'lang' => 'ko',
    'languages' => ['ko'],
    'fmt' => '%Z%n%S%n%C%n%A%n%O%n%N',
    'lfmt' => '%N%n%O%n%A%n%C%n%S, %Z',
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => null,
    'zipex' => [],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['강원도', '라선 특별시', '량강도', '자강도', '평안 남도', '평안 북도', '평양 직할시', '함경 남도', '함경 북도', '황해남도', '황해북도'],
    'sub_names' => [],
    'sub_lnames' => ['Kangwon', 'Rason', 'Ryanggang', 'Chagang', 'South Pyongan', 'North Pyongan', 'Pyongyang', 'South Hamgyong', 'North Hamgyong', 'South Hwanghae', 'North Hwanghae'],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['07', '13', '10', '04', '02', '03', '01', '08', '09', '05', '06'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
