<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/KY',
    'key' => 'KY',
    'name' => 'CAYMAN ISLANDS',
    'lang' => 'en',
    'languages' => ['en'],
    'fmt' => '%N%n%O%n%A%n%S %Z',
    'lfmt' => null,
    'require' => ['A', 'S'],
    'upper' => ['C'],
    'zip' => 'KY\\d-\\d{4}',
    'zipex' => ['KY1-1100', 'KY1-1702', 'KY2-2101'],
    'posturl' => 'http://www.caymanpost.gov.ky/',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'island',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Cayman Brac', 'Grand Cayman', 'Little Cayman'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
