<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/KZ',
    'key' => 'KZ',
    'name' => 'KAZAKHSTAN',
    'lang' => null,
    'languages' => [],
    'fmt' => '%Z%n%S%n%C%n%A%n%O%n%N',
    'lfmt' => null,
    'require' => [],
    'upper' => [],
    'zip' => '\\d{6}',
    'zipex' => ['040900', '050012'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
