<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/LB',
    'key' => 'LB',
    'name' => 'LEBANON',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C %Z',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => '(?:\\d{4})(?: ?(?:\\d{4}))?',
    'zipex' => ['2038 3054', '1107 2810', '1000'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
