<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/LI',
    'key' => 'LI',
    'name' => 'LIECHTENSTEIN',
    'lang' => null,
    'languages' => [],
    'fmt' => '%O%n%N%n%A%nFL-%Z %C',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => [],
    'zip' => '948[5-9]|949[0-8]',
    'zipex' => ['9496', '9491', '9490', '9485'],
    'posturl' => 'http://www.post.ch/db/owa/pv_plz_pack/pr_main',
    'postprefix' => 'FL-',
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
