<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/LT',
    'key' => 'LT',
    'name' => 'LITHUANIA',
    'lang' => null,
    'languages' => [],
    'fmt' => '%O%n%N%n%A%nLT-%Z %C %S',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['C'],
    'zip' => '\\d{5}',
    'zipex' => ['04340', '03500'],
    'posturl' => 'http://www.post.lt/lt/?id=316',
    'postprefix' => 'LT-',
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
