<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/LU',
    'key' => 'LU',
    'name' => 'LUXEMBOURG',
    'lang' => null,
    'languages' => [],
    'fmt' => '%O%n%N%n%A%nL-%Z %C',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['C'],
    'zip' => '\\d{4}',
    'zipex' => ['4750', '2998'],
    'posturl' => 'https://www.post.lu/fr/grandes-entreprises/solutions-postales/rechercher-un-code-postal',
    'postprefix' => 'L-',
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
