<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/LV',
    'key' => 'LV',
    'name' => 'LATVIA',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%S%n%C, %Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => [],
    'zip' => 'LV-\\d{4}',
    'zipex' => ['LV-1073', 'LV-1000'],
    'posturl' => 'http://www.pasts.lv/lv/uzzinas/nodalas/',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
