<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/MC',
    'key' => 'MC',
    'name' => 'MONACO',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%nMC-%Z %C %X',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => '980\\d{2}',
    'zipex' => ['98000', '98020', '98011', '98001'],
    'posturl' => null,
    'postprefix' => 'MC-',
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
