<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/MD',
    'key' => 'MD',
    'name' => 'Rep. MOLDOVA',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%nMD-%Z %C',
    'lfmt' => null,
    'require' => [],
    'upper' => [],
    'zip' => '\\d{4}',
    'zipex' => ['2012', '2019'],
    'posturl' => null,
    'postprefix' => 'MD-',
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
