<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/ME',
    'key' => 'ME',
    'name' => 'MONTENEGRO',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z %C',
    'lfmt' => null,
    'require' => [],
    'upper' => [],
    'zip' => '8\\d{4}',
    'zipex' => ['81257', '81258', '81217', '84314', '85366'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
