<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/MN',
    'key' => 'MN',
    'name' => 'MONGOLIA',
    'lang' => 'mn',
    'languages' => ['mn'],
    'fmt' => '%N%n%O%n%A%n%C%n%S %Z',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => '\\d{5}',
    'zipex' => ['65030', '65270'],
    'posturl' => 'http://www.zipcode.mn/',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Архангай', 'Баян-Өлгий', 'Баянхонгор', 'Булган', 'Говь-Алтай', 'Говьсүмбэр', 'Дархан-Уул', 'Дорноговь', 'Дорнод', 'Дундговь', 'Завхан', 'Орхон', 'Өвөрхангай', 'Өмнөговь', 'Сүхбаатар', 'Сэлэнгэ', 'Төв', 'Увс', 'Улаанбаатар', 'Ховд', 'Хөвсгөл', 'Хэнтий'],
    'sub_names' => [],
    'sub_lnames' => ['Arkhangai', 'Bayan-Ölgii', 'Bayankhongor', 'Bulgan', 'Govi-Altai', 'Govisümber', 'Darkhan-Uul', 'Dornogovi', 'Dornod', 'Dundgovi', 'Zavkhan', 'Orkhon', 'Ovorkhangai', 'Ömnögovi', 'Sükhbaatar', 'Selenge', 'Töv', 'Uvs', 'Ulaanbaatar', 'Khovd', 'Khovsgol', 'Khentii'],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['073', '071', '069', '067', '065', '064', '037', '063', '061', '059', '057', '035', '055', '053', '051', '049', '047', '046', '1', '043', '041', '039'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
