<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/MT',
    'key' => 'MT',
    'name' => 'MALTA',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C %Z',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C', 'Z'],
    'zip' => '[A-Z]{3} ?\\d{2,4}',
    'zipex' => ['NXR 01', 'ZTN 05', 'GPO 01', 'BZN 1130', 'SPB 6031', 'VCT 1753'],
    'posturl' => 'https://www.maltapost.com/PostCode/',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
