<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/MU',
    'key' => 'MU',
    'name' => 'MAURITIUS',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z%n%C',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C', 'Z'],
    'zip' => '\\d{3}(?:\\d{2}|[A-Z]{2}\\d{3})',
    'zipex' => ['42602'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
