<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/MZ',
    'key' => 'MZ',
    'name' => 'MOZAMBIQUE',
    'lang' => 'pt',
    'languages' => ['pt'],
    'fmt' => '%N%n%O%n%A%n%Z %C%S',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => '\\d{4}',
    'zipex' => ['1102', '1119', '3212'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Cabo Delgado', 'Cidade de Maputo', 'Gaza', 'Inhambane', 'Manica', 'Maputo', 'Nampula', 'Niassa', 'Sofala', 'Tete', 'Zambezia'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['P', 'MPM', 'G', 'I', 'B', 'L', 'N', 'A', 'S', 'T', 'Q'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
