<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/NF',
    'key' => 'NF',
    'name' => 'NORFOLK ISLAND',
    'lang' => null,
    'languages' => [],
    'fmt' => '%O%n%N%n%A%n%C %S %Z',
    'lfmt' => null,
    'require' => [],
    'upper' => ['C', 'S'],
    'zip' => '2899',
    'zipex' => ['2899'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
