<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/NG',
    'key' => 'NG',
    'name' => 'NIGERIA',
    'lang' => 'en',
    'languages' => ['en'],
    'fmt' => '%N%n%O%n%A%n%D%n%C %Z%n%S',
    'lfmt' => null,
    'require' => [],
    'upper' => ['C', 'S'],
    'zip' => '\\d{6}',
    'zipex' => ['930283', '300001', '931104'],
    'posturl' => 'http://www.nigeriapostcodes.com/',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => 'state',
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => ['Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'Federal Capital Territory', 'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa', 'Niger', 'Ogun State', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['AB', 'AD', 'AK', 'AN', 'BA', 'BY', 'BE', 'BO', 'CR', 'DE', 'EB', 'ED', 'EK', 'EN', 'FC', 'GO', 'IM', 'JI', 'KD', 'KN', 'KT', 'KE', 'KO', 'KW', 'LA', 'NA', 'NI', 'OG', 'ON', 'OS', 'OY', 'PL', 'RI', 'SO', 'TA', 'YO', 'ZA'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
