<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/NI',
    'key' => 'NI',
    'name' => 'NICARAGUA',
    'lang' => 'es',
    'languages' => ['es'],
    'fmt' => '%N%n%O%n%A%n%Z%n%C, %S',
    'lfmt' => null,
    'require' => [],
    'upper' => ['C', 'S'],
    'zip' => '\\d{5}',
    'zipex' => ['52000'],
    'posturl' => 'http://www.correos.gob.ni/codigo-postal/',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => 'department',
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => ['Boaco', 'Carazo', 'Chinandega', 'Chontales', 'Estelí', 'Granada', 'Jinotega', 'León', 'Madriz', 'Managua', 'Masaya', 'Matagalpa', 'Nueva Segovia', 'Región Autónoma de la Costa Caribe Norte', 'Región Autónoma de la Costa Caribe Sur', 'Río San Juan', 'Rivas'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => ['5[12]', '4[56]', '2[5-7]', '5[56]', '3[12]', '4[34]', '6[56]', '2[12]', '3[45]', '1[0-6]', '4[12]', '6[1-3]', '3[7-9]', '7[12]', '8[1-3]', '9[12]', '4[78]'],
    'sub_zipexs' => [],
    'sub_isoids' => ['BO', 'CA', 'CI', 'CO', 'ES', 'GR', 'JI', 'LE', 'MD', 'MN', 'MS', 'MT', 'NS', 'AN', 'AS', 'SJ', 'RI'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
