<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/NL',
    'key' => 'NL',
    'name' => 'NETHERLANDS',
    'lang' => null,
    'languages' => [],
    'fmt' => '%O%n%N%n%A%n%Z %C',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['C'],
    'zip' => '[1-9]\\d{3} ?(?:[A-RT-Z][A-Z]|S[BCE-RT-Z])',
    'zipex' => ['1234 AB', '2490 AA'],
    'posturl' => 'http://www.postnl.nl/voorthuis/',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
