<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/NO',
    'key' => 'NO',
    'name' => 'NORWAY',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z %C',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => [],
    'zip' => '\\d{4}',
    'zipex' => ['0025', '0107', '6631'],
    'posturl' => 'http://adressesok.posten.no/nb/postal_codes/search',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => 'post_town',
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
