<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/NR',
    'key' => 'NR',
    'name' => 'NAURU CENTRAL PACIFIC',
    'lang' => 'en',
    'languages' => ['en'],
    'fmt' => '%N%n%O%n%A%n%S',
    'lfmt' => null,
    'require' => ['A', 'S'],
    'upper' => [],
    'zip' => null,
    'zipex' => [],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => 'district',
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => ['Aiwo District', 'Anabar District', 'Anetan District', 'Anibare District', 'Baiti District', 'Boe District', 'Buada District', 'Denigomodu District', 'Ewa District', 'Ijuw District', 'Meneng District', 'Nibok District', 'Uaboe District', 'Yaren District'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
