<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/NZ',
    'key' => 'NZ',
    'name' => 'NEW ZEALAND',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%D%n%C %Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => [],
    'zip' => '\\d{4}',
    'zipex' => ['6001', '6015', '6332', '8252', '1030'],
    'posturl' => 'http://www.nzpost.co.nz/Cultures/en-NZ/OnlineTools/PostCodeFinder/',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
