<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/PA',
    'key' => 'PA',
    'name' => 'PANAMA (REP.)',
    'lang' => 'es',
    'languages' => ['es'],
    'fmt' => '%N%n%O%n%A%n%C%n%S',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C', 'S'],
    'zip' => null,
    'zipex' => [],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Bocas del Toro', 'Chiriquí', 'Coclé', 'Colón', 'Darién', 'Emberá', 'Guna Yala', 'Herrera', 'Los Santos', 'Naso Tjër Di', 'Ngäbe-Buglé', 'Panamá', 'Panamá Oeste', 'Veraguas'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['1', '4', '2', '3', '5', 'EM', 'KY', '6', '7', 'NT', 'NB', '8', '10', '9'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
