<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/PE',
    'key' => 'PE',
    'name' => 'PERU',
    'lang' => 'es',
    'languages' => ['es'],
    'fmt' => '%N%n%O%n%A%n%C %Z%n%S',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => '(?:LIMA \\d{1,2}|CALLAO 0?\\d)|[0-2]\\d{4}',
    'zipex' => ['LIMA 23', 'LIMA 42', 'CALLAO 2', '02001'],
    'posturl' => 'http://www.codigopostal.gob.pe/pages/invitado/consulta.jsf',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'district',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Amazonas', 'Áncash', 'Apurímac', 'Arequipa', 'Ayacucho', 'Cajamarca', 'Callao', 'Cuzco', 'Gobierno Regional de Lima', 'Huancavelica', 'Huánuco', 'Ica', 'Junín', 'La Libertad', 'Lambayeque', 'Loreto', 'Madre de Dios', 'Moquegua', 'Municipalidad Metropolitana de Lima', 'Pasco', 'Piura', 'Puno', 'San Martín', 'Tacna', 'Tumbes', 'Ucayali'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['AMA', 'ANC', 'APU', 'ARE', 'AYA', 'CAJ', 'CAL', 'CUS', 'LIM', 'HUV', 'HUC', 'ICA', 'JUN', 'LAL', 'LAM', 'LOR', 'MDD', 'MOQ', 'LMA', 'PAS', 'PIU', 'PUN', 'SAM', 'TAC', 'TUM', 'UCA'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
