<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/PF',
    'key' => 'PF',
    'name' => 'FRENCH POLYNESIA',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z %C %S',
    'lfmt' => null,
    'require' => ['A', 'C', 'S', 'Z'],
    'upper' => ['C', 'S'],
    'zip' => '987\\d{2}',
    'zipex' => ['98709'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'island',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
