<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/PG',
    'key' => 'PG',
    'name' => 'PAPUA NEW GUINEA',
    'lang' => 'tpi',
    'languages' => ['tpi', 'en', 'ho'],
    'fmt' => '%N%n%O%n%A%n%C %Z %S',
    'lfmt' => null,
    'require' => ['A', 'C', 'S'],
    'upper' => ['C'],
    'zip' => '\\d{3}',
    'zipex' => ['111'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Bougainville', 'Central Provins', 'Enga Provins', 'Gulf Provins', 'Hela Provins', 'Is Niu Briten Provins', 'Is Sepik Provins', 'Isten Hailans Provins', 'Jiwaka Provins', 'Madang Provins', 'Manus Provins', 'Milen Be Provins', 'Morobe Provins', 'Nesenel Kapitol Distrik', 'Niu Ailan Provins', 'Oro Provins', 'Sandaun Provins', 'Sauten Hailans Provins', 'Simbu Provins', 'Wes Niu Briten Provins', 'Western Hailans Provins', 'Western Provins'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['NSB', 'CPM', 'EPW', 'GPK', 'HLA', 'EBR', 'ESW', 'EHG', 'JWK', 'MPM', 'MRL', 'MBA', 'MPL', 'NCD', 'NIK', 'NPP', 'SAN', 'SHM', 'CPK', 'WBK', 'WHM', 'WPD'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
