<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/PG',
    'key' => 'PG',
    'name' => 'PAPUA NEW GUINEA',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C %Z %S',
    'lfmt' => null,
    'require' => ['A', 'C', 'S'],
    'upper' => ['C'],
    'zip' => '\\d{3}',
    'zipex' => ['111'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
