<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/PL',
    'key' => 'PL',
    'name' => 'POLAND',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z %C',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => [],
    'zip' => '\\d{2}-\\d{3}',
    'zipex' => ['00-950', '05-470', '48-300', '32-015', '00-940'],
    'posturl' => 'http://kody.poczta-polska.pl/',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
