<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/PM',
    'key' => 'PM',
    'name' => 'ST. PIERRE AND MIQUELON',
    'lang' => null,
    'languages' => [],
    'fmt' => '%O%n%N%n%A%n%Z %C %X',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['A', 'C', 'X'],
    'zip' => '9[78]5\\d{2}',
    'zipex' => ['97500'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
