<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/PR',
    'key' => 'PR',
    'name' => 'PUERTO RICO',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C PR %Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['A', 'C', 'N', 'O'],
    'zip' => '(00[679]\\d{2})(?:[ \\-](\\d{4}))?',
    'zipex' => ['00930'],
    'posturl' => 'http://zip4.usps.com/zip4/welcome.jsp',
    'postprefix' => 'PR ',
    'zip_name_type' => 'zip',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
