<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/PT',
    'key' => 'PT',
    'name' => 'PORTUGAL',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z %C',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['C'],
    'zip' => '\\d{4}-\\d{3}',
    'zipex' => ['2725-079', '1250-096', '1201-950', '2860-571', '1208-148'],
    'posturl' => 'http://www.ctt.pt/feapl_2/app/open/tools.jspx?tool=1',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
