<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/PW',
    'key' => 'PW',
    'name' => 'PALAU',
    'lang' => 'pau',
    'languages' => ['pau', 'en'],
    'fmt' => '%N%n%O%n%A%n%C %S %Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'S', 'Z'],
    'upper' => ['A', 'C', 'N', 'O', 'S'],
    'zip' => '(969(?:39|40))(?:[ \\-](\\d{4}))?',
    'zipex' => ['96940'],
    'posturl' => 'http://zip4.usps.com/zip4/welcome.jsp',
    'postprefix' => null,
    'zip_name_type' => 'zip',
    'state_name_type' => 'state',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Aimeliik', 'Airai', 'Angaur', 'Hatohobei', 'Kayangel', 'Koror', 'Melekeok', 'Ngaraard', 'Ngarchelong', 'Ngardmau', 'Ngaremlengui', 'Ngatpang', 'Ngchesar', 'Ngiwal', 'Peleliu', 'Sonsorol'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['002', '004', '010', '050', '100', '150', '212', '214', '218', '222', '227', '224', '226', '228', '350', '370'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
