<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/RO',
    'key' => 'RO',
    'name' => 'ROMANIA',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z %S %C',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['A', 'C'],
    'zip' => '\\d{6}',
    'zipex' => ['060274', '061357', '200716'],
    'posturl' => 'http://www.posta-romana.ro/zip_codes',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
