<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/SE',
    'key' => 'SE',
    'name' => 'SWEDEN',
    'lang' => null,
    'languages' => [],
    'fmt' => '%O%n%N%n%A%nSE-%Z %C',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['C'],
    'zip' => '\\d{3} ?\\d{2}',
    'zipex' => ['11455', '12345', '10500'],
    'posturl' => 'https://www.postnord.se/online-verktyg/verktyg/sok/sok-postnummer-och-adress',
    'postprefix' => 'SE-',
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'post_town',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
