<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/SG',
    'key' => 'SG',
    'name' => 'REP. OF SINGAPORE',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%nSINGAPORE %Z',
    'lfmt' => null,
    'require' => ['A', 'Z'],
    'upper' => ['C'],
    'zip' => '\\d{6}',
    'zipex' => ['546080', '308125', '408600'],
    'posturl' => 'https://www.singpost.com/find-postal-code',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
