<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/SI',
    'key' => 'SI',
    'name' => 'SLOVENIA',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%nSI-%Z %C',
    'lfmt' => null,
    'require' => [],
    'upper' => [],
    'zip' => '\\d{4}',
    'zipex' => ['4000', '1001', '2500'],
    'posturl' => null,
    'postprefix' => 'SI-',
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
