<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/SK',
    'key' => 'SK',
    'name' => 'SLOVAKIA',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z %C',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => [],
    'zip' => '\\d{3} ?\\d{2}',
    'zipex' => ['010 01', '023 14', '972 48', '921 01', '975 99'],
    'posturl' => 'http://psc.posta.sk',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
