<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/SL',
    'key' => 'SL',
    'name' => 'SIERRA LEONE',
    'lang' => null,
    'languages' => [],
    'fmt' => null,
    'lfmt' => null,
    'require' => [],
    'upper' => [],
    'zip' => null,
    'zipex' => [],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
