<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/SM',
    'key' => 'SM',
    'name' => 'SAN MARINO',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z %C',
    'lfmt' => null,
    'require' => ['A', 'Z'],
    'upper' => ['C'],
    'zip' => '4789\\d',
    'zipex' => ['47890', '47891', '47895', '47899'],
    'posturl' => 'http://www.poste.it/online/cercacap/',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
