<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/SR',
    'key' => 'SR',
    'name' => 'SURINAME',
    'lang' => 'nl',
    'languages' => ['nl'],
    'fmt' => '%N%n%O%n%A%n%C%n%S',
    'lfmt' => null,
    'require' => [],
    'upper' => ['A', 'S'],
    'zip' => null,
    'zipex' => [],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => ['Brokopondo', 'Commewijne', 'Coronie', 'Marowijne', 'Nickerie', 'Para', 'Paramaribo', 'Saramacca', 'Sipaliwini', 'Wanica'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['BR', 'CM', 'CR', 'MA', 'NI', 'PR', 'PM', 'SA', 'SI', 'WA'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
