<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/TC',
    'key' => 'TC',
    'name' => 'TURKS AND CAICOS ISLANDS',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C%n%Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['C', 'Z'],
    'zip' => 'TKCA 1ZZ',
    'zipex' => ['TKCA 1ZZ'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
