<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/TV',
    'key' => 'TV',
    'name' => 'TUVALU',
    'lang' => 'tyv',
    'languages' => ['tyv'],
    'fmt' => '%N%n%O%n%A%n%C%n%S',
    'lfmt' => null,
    'require' => [],
    'upper' => ['A', 'C', 'S'],
    'zip' => null,
    'zipex' => [],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => 'island',
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => ['Funafuti', 'Nanumanga', 'Nanumea', 'Niulakita', 'Niutao', 'Nui', 'Nukufetau', 'Nukulaelae', 'Vaitupu'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['FUN', 'NMG', 'NMA', '', 'NIT', 'NUI', 'NKF', 'NKL', 'VAI'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
