<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/UM',
    'key' => 'UM',
    'name' => 'UNITED STATES MINOR OUTLYING ISLANDS',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C %S %Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'S'],
    'upper' => ['A', 'C', 'N', 'O', 'S'],
    'zip' => '96898',
    'zipex' => ['96898'],
    'posturl' => 'http://zip4.usps.com/zip4/welcome.jsp',
    'postprefix' => null,
    'zip_name_type' => 'zip',
    'state_name_type' => 'state',
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
