<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/UY',
    'key' => 'UY',
    'name' => 'URUGUAY',
    'lang' => 'es',
    'languages' => ['es'],
    'fmt' => '%N%n%O%n%A%n%Z %C %S',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C', 'S'],
    'zip' => '\\d{5}',
    'zipex' => ['11600'],
    'posturl' => 'http://www.correo.com.uy/index.asp?codPag=codPost&switchMapa=codPost',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Artigas', 'Canelones', 'Cerro Largo', 'Colonia', 'Durazno', 'Flores', 'Florida', 'Lavalleja', 'Maldonado', 'Montevideo', 'Paysandú', 'Río Negro', 'Rivera', 'Rocha', 'Salto', 'San José', 'Soriano', 'Tacuarembó', 'Treinta y Tres'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => ['55', '9[01]|1[456]', '37', '70|75204', '97', '85', '94|9060|97005', '30', '20', '1|91600', '60', '65|60002', '40', '27', '50', '80', '75|70003', '45', '33|30203|30204|30302|37007'],
    'sub_zipexs' => [],
    'sub_isoids' => ['AR', 'CA', 'CL', 'CO', 'DU', 'FS', 'FD', 'LA', 'MA', 'MO', 'PA', 'RN', 'RV', 'RO', 'SA', 'SJ', 'SO', 'TA', 'TT'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
