<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/UZ',
    'key' => 'UZ',
    'name' => 'UZBEKISTAN',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%Z %C%n%S',
    'lfmt' => null,
    'require' => [],
    'upper' => ['C', 'S'],
    'zip' => '\\d{6}',
    'zipex' => ['702100', '700000'],
    'posturl' => 'http://www.pochta.uz/ru/uslugi/indexsearch.html',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => null,
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
