<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/UZ',
    'key' => 'UZ',
    'name' => 'UZBEKISTAN',
    'lang' => 'uz',
    'languages' => ['uz', 'ru'],
    'fmt' => '%N%n%O%n%A%n%Z %C%n%S',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C', 'S'],
    'zip' => '\\d{6}',
    'zipex' => ['702100', '700000'],
    'posturl' => 'https://uz.post/ru/mening-pochta-indeksim',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => ['Andijon Viloyati', 'Buxoro Viloyati', 'Farg\'ona Viloyati', 'Jizzax Viloyati', 'Namangan Viloyati', 'Navoiy Viloyati', 'Qashqadaryo Viloyati', 'Qoraqalpog’iston Respublikasi', 'Samarqand Viloyati', 'Sirdaryo Viloyati', 'Surxondaryo Viloyati', 'Toshkent', 'Toshkent Viloyati', 'Xorazm Viloyati'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['AN', 'BU', 'FA', 'JI', 'NG', 'NW', 'QA', 'QR', 'SA', 'SI', 'SU', 'TK', 'TO', 'XO'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
