<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/VC',
    'key' => 'VC',
    'name' => 'SAINT VINCENT AND THE GRENADINES (ANTILLES)',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%C %Z',
    'lfmt' => null,
    'require' => ['A', 'C'],
    'upper' => ['C'],
    'zip' => 'VC\\d{4}',
    'zipex' => ['VC0100', 'VC0110', 'VC0400'],
    'posturl' => 'http://www.svgpost.gov.vc/?option=com_content&view=article&id=3&Itemid=16',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
