<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/VE',
    'key' => 'VE',
    'name' => 'VENEZUELA',
    'lang' => 'es',
    'languages' => ['es'],
    'fmt' => '%N%n%O%n%A%n%C %Z, %S',
    'lfmt' => null,
    'require' => ['A', 'C', 'S'],
    'upper' => ['C', 'S'],
    'zip' => '\\d{4}',
    'zipex' => ['1010', '3001', '8011', '1020'],
    'posturl' => 'http://postcode.vnpost.vn/services/search.aspx',
    'postprefix' => null,
    'zip_name_type' => null,
    'state_name_type' => 'state',
    'locality_name_type' => null,
    'sublocality_name_type' => null,
    'sub_keys' => ['Amazonas', 'Anzoátegui', 'Apure', 'Aragua', 'Barinas', 'Bolívar', 'Carabobo', 'Cojedes', 'Delta Amacuro', 'Dependencias Federales', 'Distrito Federal', 'Falcón', 'Guárico', 'Lara', 'Mérida', 'Miranda', 'Monagas', 'Nueva Esparta', 'Portuguesa', 'Sucre', 'Táchira', 'Trujillo', 'Vargas', 'Yaracuy', 'Zulia'],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => ['Z', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'Y', 'W', 'A', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'X', 'U', 'V'],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
