<?php return \Sunaoka\AddressData\Address::__set_state(array(
   'id' => 'data/VN',
   'key' => 'VN',
   'name' => 'VIET NAM',
   'lang' => 'vi',
   'languages' => 
  array (
    0 => 'vi',
  ),
   'fmt' => '%N%n%O%n%A%n%C%n%S %Z',
   'lfmt' => '%N%n%O%n%A%n%C%n%S %Z',
   'require' => 
  array (
  ),
   'upper' => 
  array (
  ),
   'zip' => '\\d{5}\\d?',
   'zipex' => 
  array (
    0 => '70010',
    1 => '55999',
  ),
   'posturl' => 'http://postcode.vnpost.vn/services/search.aspx',
   'postprefix' => NULL,
   'zip_name_type' => NULL,
   'state_name_type' => NULL,
   'locality_name_type' => NULL,
   'sublocality_name_type' => NULL,
   'sub_keys' => 
  array (
    0 => 'An Giang',
    1 => 'Bà Rịa–Vũng Tàu',
    2 => 'Bạc Liêu',
    3 => 'Bắc Giang',
    4 => 'Bắc Kạn',
    5 => 'Bắc Ninh',
    6 => 'Bến Tre',
    7 => 'Bình Dương',
    8 => 'Bình Định',
    9 => 'Bình Phước',
    10 => 'Bình Thuận',
    11 => 'Cà Mau',
    12 => 'Cao Bằng',
    13 => 'Cần Thơ',
    14 => 'Đà Nẵng',
    15 => 'Đắk Lắk',
    16 => 'Đăk Nông',
    17 => 'Điện Biên',
    18 => 'Đồng Nai',
    19 => 'Đồng Tháp',
    20 => 'Gia Lai',
    21 => 'Hà Giang',
    22 => 'Hà Nam',
    23 => 'Hà Nội',
    24 => 'Hà Tĩnh',
    25 => 'Hải Dương',
    26 => 'Hải Phòng',
    27 => 'Hậu Giang',
    28 => 'Hòa Bình',
    29 => 'Hưng Yên',
    30 => 'Khánh Hòa',
    31 => 'Kiên Giang',
    32 => 'Kon Tum',
    33 => 'Lai Châu',
    34 => 'Lạng Sơn',
    35 => 'Lào Cai',
    36 => 'Lâm Đồng',
    37 => 'Long An',
    38 => 'Nam Định',
    39 => 'Nghệ An',
    40 => 'Ninh Bình',
    41 => 'Ninh Thuận',
    42 => 'Phú Thọ',
    43 => 'Phú Yên',
    44 => 'Quảng Bình',
    45 => 'Quảng Nam',
    46 => 'Quảng Ngãi',
    47 => 'Quảng Ninh',
    48 => 'Quảng Trị',
    49 => 'Sóc Trăng',
    50 => 'Sơn La',
    51 => 'Tây Ninh',
    52 => 'Thái Bình',
    53 => 'Thái Nguyên',
    54 => 'Thanh Hóa',
    55 => 'Thành phố Hồ Chí Minh',
    56 => 'Thừa Thiên–Huế',
    57 => 'Tiền Giang',
    58 => 'Trà Vinh',
    59 => 'Tuyên Quang',
    60 => 'Vĩnh Long',
    61 => 'Vĩnh Phúc',
    62 => 'Yên Bái',
  ),
   'sub_names' => 
  array (
  ),
   'sub_lnames' => 
  array (
    0 => 'An Giang Province',
    1 => 'Ba Ria-Vung Tau Province',
    2 => 'Bac Lieu Province',
    3 => 'Bac Giang Province',
    4 => 'Bac Kan Province',
    5 => 'Bac Ninh Province',
    6 => 'Ben Tre Province',
    7 => 'Binh Duong Province',
    8 => 'Binh Dinh Province',
    9 => 'Binh Phuoc Province',
    10 => 'Binh Thuan Province',
    11 => 'Ca Mau Province',
    12 => 'Cao Bang Province',
    13 => 'Can Tho City',
    14 => 'Da Nang City',
    15 => 'Dak Lak Province',
    16 => 'Dak Nong Province',
    17 => 'Dien Bien Province',
    18 => 'Dong Nai Province',
    19 => 'Dong Thap Province',
    20 => 'Gia Lai Province',
    21 => 'Ha Giang Province',
    22 => 'Ha Nam Province',
    23 => 'Hanoi City',
    24 => 'Ha Tinh Province',
    25 => 'Hai Duong Province',
    26 => 'Haiphong City',
    27 => 'Hau Giang Province',
    28 => 'Hoa Binh Province',
    29 => 'Hung Yen Province',
    30 => 'Khanh Hoa Province',
    31 => 'Kien Giang Province',
    32 => 'Kon Tum Province',
    33 => 'Lai Chau Province',
    34 => 'Lang Song Province',
    35 => 'Lao Cai Province',
    36 => 'Lam Dong Province',
    37 => 'Long An Province',
    38 => 'Nam Dinh Province',
    39 => 'Nghe An Province',
    40 => 'Ninh Binh Province',
    41 => 'Ninh Thuan Province',
    42 => 'Phu Tho Province',
    43 => 'Phu Yen Province',
    44 => 'Quang Binh Province',
    45 => 'Quang Nam Province',
    46 => 'Quang Ngai Province',
    47 => 'Quang Ninh Province',
    48 => 'Quang Tri Province',
    49 => 'Soc Trang Province',
    50 => 'Son La Province',
    51 => 'Tay Ninh Province',
    52 => 'Thai Binh Province',
    53 => 'Thai Nguyen Province',
    54 => 'Thanh Hoa Province',
    55 => 'Ho Chi Minh City',
    56 => 'Thua Thien-Hue Province',
    57 => 'Tien Giang Province',
    58 => 'Tra Vinh Province',
    59 => 'Tuyen Quang Province',
    60 => 'Vinh Long Province',
    61 => 'Vinh Phuc Province',
    62 => 'Yen Bai Province',
  ),
   'sub_zips' => 
  array (
  ),
   'sub_zipexs' => 
  array (
  ),
   'sub_isoids' => 
  array (
    0 => '44',
    1 => '43',
    2 => '55',
    3 => '54',
    4 => '53',
    5 => '56',
    6 => '50',
    7 => '57',
    8 => '31',
    9 => '58',
    10 => '40',
    11 => '59',
    12 => '04',
    13 => 'CT',
    14 => 'DN',
    15 => '33',
    16 => '72',
    17 => '71',
    18 => '39',
    19 => '45',
    20 => '30',
    21 => '03',
    22 => '63',
    23 => 'HN',
    24 => '23',
    25 => '61',
    26 => 'HP',
    27 => '73',
    28 => '14',
    29 => '66',
    30 => '34',
    31 => '47',
    32 => '28',
    33 => '01',
    34 => '09',
    35 => '02',
    36 => '35',
    37 => '41',
    38 => '67',
    39 => '22',
    40 => '18',
    41 => '36',
    42 => '68',
    43 => '32',
    44 => '24',
    45 => '27',
    46 => '29',
    47 => '13',
    48 => '25',
    49 => '52',
    50 => '05',
    51 => '37',
    52 => '20',
    53 => '69',
    54 => '21',
    55 => 'SG',
    56 => '26',
    57 => '46',
    58 => '51',
    59 => '07',
    60 => '49',
    61 => '70',
    62 => '06',
  ),
   'sub_mores' => 
  array (
  ),
   'sub_xzips' => 
  array (
  ),
   'sub_xrequires' => 
  array (
  ),
));