<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/WF',
    'key' => 'WF',
    'name' => 'WALLIS AND FUTUNA ISLANDS',
    'lang' => null,
    'languages' => [],
    'fmt' => '%O%n%N%n%A%n%Z %C %X',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['A', 'C', 'X'],
    'zip' => '986\\d{2}',
    'zipex' => ['98600'],
    'posturl' => null,
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
