<?php return \Sunaoka\AddressData\Address::__set_state([
    'id' => 'data/ZA',
    'key' => 'ZA',
    'name' => 'SOUTH AFRICA',
    'lang' => null,
    'languages' => [],
    'fmt' => '%N%n%O%n%A%n%D%n%C%n%Z',
    'lfmt' => null,
    'require' => ['A', 'C', 'Z'],
    'upper' => ['C'],
    'zip' => '\\d{4}',
    'zipex' => ['0083', '1451', '0001'],
    'posturl' => 'https://www.postoffice.co.za/Questions/postalcode.html',
    'postprefix' => null,
    'zip_name_type' => 'postal',
    'state_name_type' => 'province',
    'locality_name_type' => 'city',
    'sublocality_name_type' => 'suburb',
    'sub_keys' => [],
    'sub_names' => [],
    'sub_lnames' => [],
    'sub_zips' => [],
    'sub_zipexs' => [],
    'sub_isoids' => [],
    'sub_mores' => [],
    'sub_xzips' => [],
    'sub_xrequires' => []
]);
