name: update

on:
  workflow_dispatch:
  schedule:
    - cron: '5 1 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          composer config --global --no-plugins allow-plugins true
          composer install --quiet --no-ansi --prefer-dist --no-progress --no-interaction

      - name: Update
        run: php builder/address-data-update.php

      - name: Count changes
        id: changes
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update Address Data
          delete-branch: true
          title: Update Address Data
          body: |
            Address Data have been updated.
        if: steps.changes.outcome == 'failure'
